export const NOTE_TYPE_LIST_REQUEST = "NOTE_TYPE_LIST_REQUEST";
export const NOTE_TYPE_LIST_SUCCESS = "NOTE_TYPE_LIST_SUCCESS";
export const NOTE_TYPE_LIST_FAIL = "NOTE_TYPE_LIST_FAIL";

export const NOTE_TYPE_CREATE_REQUEST = "NOTE_TYPE_CREATE_REQUEST";
export const NOTE_TYPE_CREATE_SUCCESS = "NOTE_TYPE_CREATE_SUCCESS";
export const NOTE_TYPE_CREATE_FAIL = "NOTE_TYPE_CREATE_FAIL";
export const NOTE_TYPE_CREATE_RESET = "NOTE_TYPE_CREATE_RESET";

export const NOTE_TYPE_DELETE_REQUEST = "NOTE_TYPE_DELETE_REQUEST";
export const NOTE_TYPE_DELETE_SUCCESS = "NOTE_TYPE_DELETE_SUCCESS";
export const NOTE_TYPE_DELETE_FAIL = "NOTE_TYPE_DELETE_FAIL";
export const NOTE_TYPE_DELETE_RESET = "NOTE_TYPE_DELETE_RESET";

export const NOTE_TYPE_EDIT_REQUEST = "NOTE_TYPE_EDIT_REQUEST";
export const NOTE_TYPE_EDIT_SUCCESS = "NOTE_TYPE_EDIT_SUCCESS";
export const NOTE_TYPE_EDIT_FAIL = "NOTE_TYPE_EDIT_FAIL";

export const NOTE_TYPE_UPDATE_REQUEST = "NOTE_TYPE_UPDATE_REQUEST";
export const NOTE_TYPE_UPDATE_SUCCESS = "NOTE_TYPE_UPDATE_SUCCESS";
export const NOTE_TYPE_UPDATE_FAIL = "NOTE_TYPE_UPDATE_FAIL";
export const NOTE_TYPE_UPDATE_RESET = "NOTE_TYPE_UPDATE_RESET";
