export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DETAILS_REQUEST = "ORDER_DETAILS_REQUEST";
export const ORDER_DETAILS_SUCCESS = "ORDER_DETAILS_SUCCESS";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const ORDER_ID_REQUEST = "ORDER_ID_REQUEST";
export const ORDER_ID_SUCCESS = "ORDER_ID_SUCCESS";
export const ORDER_ID_FAIL = "ORDER_ID_FAIL";

export const ORDER_USER_ID_REQUEST = "ORDER_USER_ID_REQUEST";
export const ORDER_USER_ID_SUCCESS = "ORDER_USER_ID_SUCCESS";
export const ORDER_USER_ID_FAIL = "ORDER_USER_ID_FAIL";

export const ORDER_STATUS_REQUEST = "ORDER_STATUS_REQUEST";
export const ORDER_STATUS_SUCCESS = "ORDER_STATUS_SUCCESS";
export const ORDER_STATUS_FAIL = "ORDER_STATUS_FAIL";
export const ORDER_STATUS_RESET = "ORDER_STATUS_RESET";

export const ORDER_DEBT_REQUEST = "ORDER_DEBT_REQUEST";
export const ORDER_DEBT_SUCCESS = "ORDER_DEBT_SUCCESS";
export const ORDER_DEBT_FAIL = "ORDER_DEBT_FAIL";
export const ORDER_DEBT_RESET = "ORDER_DEBT_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";

export const ORDER_EDIT_REQUEST = "ORDER_EDIT_REQUEST";
export const ORDER_EDIT_SUCCESS = "ORDER_EDIT_SUCCESS";
export const ORDER_EDIT_FAIL = "ORDER_EDIT_FAIL";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";
