export const ROUTE_LIST_REQUEST = "ROUTE_LIST_REQUEST";
export const ROUTE_LIST_SUCCESS = "ROUTE_LIST_SUCCESS";
export const ROUTE_LIST_FAIL = "ROUTE_LIST_FAIL";

export const ROUTE_CREATE_REQUEST = "ROUTE_CREATE_REQUEST";
export const ROUTE_CREATE_SUCCESS = "ROUTE_CREATE_SUCCESS";
export const ROUTE_CREATE_FAIL = "ROUTE_CREATE_FAIL";
export const ROUTE_CREATE_RESET = "ROUTE_CREATE_RESET";

export const ROUTE_DELETE_REQUEST = "ROUTE_DELETE_REQUEST";
export const ROUTE_DELETE_SUCCESS = "ROUTE_DELETE_SUCCESS";
export const ROUTE_DELETE_FAIL = "ROUTE_DELETE_FAIL";
export const ROUTE_DELETE_RESET = "ROUTE_DELETE_RESET";

export const ROUTE_EDIT_REQUEST = "ROUTE_EDIT_REQUEST";
export const ROUTE_EDIT_SUCCESS = "ROUTE_EDIT_SUCCESS";
export const ROUTE_EDIT_FAIL = "ROUTE_EDIT_FAIL";

export const ROUTE_UPDATE_REQUEST = "ROUTE_UPDATE_REQUEST";
export const ROUTE_UPDATE_SUCCESS = "ROUTE_UPDATE_SUCCESS";
export const ROUTE_UPDATE_FAIL = "ROUTE_UPDATE_FAIL";
export const ROUTE_UPDATE_RESET = "ROUTE_UPDATE_RESET";
