export const TRANSACTION_GET_ID_REQUEST = "TRANSACTION_GET_ID_REQUEST";
export const TRANSACTION_GET_ID_SUCCESS = "TRANSACTION_GET_ID_SUCCESS";
export const TRANSACTION_GET_ID_FAIL = "TRANSACTION_GET_ID_FAIL";

export const TRANSACTION_GET_USER_ID_REQUEST = "TRANSACTION_GET_USER_ID_REQUEST";
export const TRANSACTION_GET_USER_ID_SUCCESS = "TRANSACTION_GET_USER_ID_SUCCESS";
export const TRANSACTION_GET_USER_ID_FAIL = "TRANSACTION_GET_USER_ID_FAIL";
